services:
  bot:
    image: ${DOCKERHUB_USERNAME}/timtimbot:latest # Используем образ из DockerHub
    container_name: timtimbot
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    # ports:
      # - "${HEALTHCHECK_PORT}:${HEALTHCHECK_PORT}"

  db:
    image: postgres:15-alpine
    container_name: chatdetective-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "7779:5432"
    volumes:
      - /var/lib/postgresql/timtimbot:/var/lib/postgresql/data # Данные хранятся на VPS, не в контейнере
    # Важно: volume должен быть на VPS, чтобы данные не терялись при пересоздании контейнера 